### PR TITLE
Add support bahasa

### PR DESCRIPTION
**Pull request by suryamudti**

### CODE REVIEW

**Comment by pandubaraja** [comment]
Hi @suryamudti please merge your branch with updated `master`. So the `.gitignore` updated to the latest version and the `.idea` folder will be ignored.

Thank you! 🙏 

Ref: https://stackoverflow.com/questions/32384473/gitignore-not-ignoring-idea-path

**Comment by suryamudti** [comment]
Done.
Thanks for the guidance,

**Comment by fajarnuha** [comment]
I notice your PR isn't clean, please update your branch with master branch so we can see your changes more clearly

**Comment by pandubaraja** [comment]
Hi @suryamudti could you create a new `branch` from `master`

After that you can use **cherry-pick** to apply the only needed `commits` from the **previous branch** you work on to the **new branch**? 

So we can see your changes more clearly as @fajarnuha said. 👓 👨‍💻

**Comment by suryamudti** [comment]
Hi @pandubaraja,
Sure, will try it.
Thanks

**Comment by rizmaulana** [comment]
Cherry pick commit here https://github.com/rizmaulana/kotlin-mvvm-covid19/pull/31

**Pull request closed without merging**
