### PR TITLE
add menu localization for change the language

### PR DESCRIPTION
**Pull request by Faresapn**
this feature to change languange with menu bar , so we can easily change the language

### CODE REVIEW

**Comment by rizmaulana** [comment]
Is it to change the entire system language setting? I think it would be better if we only change default locale on our app

**Comment by Faresapn** [comment]
because sometimes the default language is English and he wants to change
the language to Indonesian and sometimes confused where to set

Pada tanggal Rab, 18 Mar 2020 pukul 20.17 Rizki Maulana <
notifications@github.com> menulis:

**Comment by fajarnuha** [comment]
I think changing system language isn't this app's job, @rizmaulana is right, changing default locale on app looks better

**Comment by Faresapn** [comment]
okey good luck

**Pull request closed without merging**
