### PR TITLE
Update string bahasa

### PR DESCRIPTION
**Pull request by suryamudti**
Hi mas @rizmaulana 
Here for the screenshoots
[dashboard](https://ibb.co/jkgYXjg)
[detail](https://ibb.co/j8HxTVv)

Description : only add string support for Bahasa, this for support general public in indonesia

Hope this green to proceed 🙏🏻
Still need your advice
Thank you,

### CODE REVIEW

**Comment by fajarnuha** [comment]
LGTM 🎉

**Comment by pandubaraja** [comment]
Nice at last! @suryamudti 🎉

**Comment by rizmaulana** [comment]
Thanks for PR mas @suryamudti 🎉

**Comment by suryamudti** [comment]
Alhamdulillah,
With pleasure mas, @rizmaulana 👍

**Comment by suryamudti** [comment]
Thank you all !
😁🙏🏻

**Pull request merged**
